# - name: set fact conf_dir
- name: set fact conf_dir
  set_fact: conf_dir={{ pb_conf_dir }}

#Use systemd for the following distributions:
#Ubuntu 15 and up
#Debian 8 and up
#Centos 7 and up
#Relies on logstash distribution installing a serviced script to determine whether one should be copied.

- name: set fact use_system_d
  set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

