---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: include prerequisites.yml
  include: prerequisites.yml
  tags:
      - always

- name: include filebeat-main.yml
  include: filebeat/filebeat-main.yml
  tags:
      - filebeat
  when: '"filebeat" in enabled_collectors'

- name: include packetbeat-main.yml
  include: packetbeat/packetbeat-main.yml
  tags:
      - packetbeat
  when: '"packetbeat" in enabled_collectors'

- name: include metricbeat-main.yml
  include: metricbeat/metricbeat-main.yml
  tags:
      - metricbeat
  when: '"metricbeat" in enabled_collectors'